version: "3.8"
services:
  
  linter-app:
    container_name: linter-app
    image: cptteddy/linter-app:0.0.1
    depends_on:
      - linter-server
      - morphir-server
    ports:
      - 8090:8090
    networks:
      - linter

  linter-server:
    container_name: linter-server
    image: cptteddy/linter-server:0.0.1
    ports:
      - 8091:8091
    networks:
      - linter

  morphir-server:
    container_name: morphir-server
    image: cptteddy/morphir-server:0.0.1
    ports:
      - 8092:8092
    networks:
      - linter

networks:
  linter: {}